import type { Candidate, Project } from "./matching-engine"

export const sampleCandidates: Candidate[] = [
  {
    id: "c1",
    name: "Sarah Chen",
    email: "sarah.chen@email.com",
    avatar: "SC",
    skills: [
      { name: "React", level: 88, category: "framework", yearsOfExperience: 3, certifications: ["Meta React Developer"] },
      { name: "TypeScript", level: 82, category: "programming", yearsOfExperience: 2.5 },
      { name: "Node.js", level: 75, category: "programming", yearsOfExperience: 2 },
      { name: "PostgreSQL", level: 70, category: "database", yearsOfExperience: 1.5 },
      { name: "Python", level: 65, category: "programming", yearsOfExperience: 2 },
      { name: "AWS", level: 55, category: "cloud", yearsOfExperience: 1 },
      { name: "Git", level: 85, category: "devops", yearsOfExperience: 3 },
      { name: "Communication", level: 90, category: "softskill", yearsOfExperience: 4 },
    ],
    education: { degree: "B.S.", field: "Computer Science", institution: "Stanford University", gpa: 3.8, graduationYear: 2024 },
    experience: [
      { title: "Frontend Developer Intern", company: "Airbnb", durationMonths: 6, skills: ["React", "TypeScript", "Node.js"] },
      { title: "Teaching Assistant", company: "Stanford CS Department", durationMonths: 12, skills: ["Python", "Communication"] },
    ],
    projects: [
      { name: "E-Commerce Platform", description: "Full-stack shopping platform", skills: ["React", "Node.js", "PostgreSQL"], role: "Lead Developer", outcome: "1000+ users" },
      { name: "AI Chat Application", description: "Real-time chat with AI integration", skills: ["TypeScript", "React", "Python"], role: "Full Stack Developer" },
    ],
    preferences: { desiredRoles: ["Frontend Engineer", "Full Stack Developer"], preferredIndustries: ["Technology", "E-Commerce"], remote: true },
  },
  {
    id: "c2",
    name: "Marcus Johnson",
    email: "marcus.j@email.com",
    avatar: "MJ",
    skills: [
      { name: "Python", level: 92, category: "programming", yearsOfExperience: 4, certifications: ["AWS ML Specialty"] },
      { name: "TensorFlow", level: 85, category: "ai-ml", yearsOfExperience: 2.5 },
      { name: "SQL", level: 80, category: "database", yearsOfExperience: 3 },
      { name: "Data Analysis", level: 88, category: "data", yearsOfExperience: 3 },
      { name: "R", level: 72, category: "programming", yearsOfExperience: 2 },
      { name: "Docker", level: 65, category: "devops", yearsOfExperience: 1.5 },
      { name: "Tableau", level: 78, category: "data", yearsOfExperience: 2 },
      { name: "Teamwork", level: 85, category: "softskill", yearsOfExperience: 4 },
    ],
    education: { degree: "M.S.", field: "Data Science", institution: "MIT", gpa: 3.9, graduationYear: 2024 },
    experience: [
      { title: "Data Science Intern", company: "Netflix", durationMonths: 4, skills: ["Python", "TensorFlow", "SQL"] },
      { title: "Research Assistant", company: "MIT AI Lab", durationMonths: 18, skills: ["Python", "TensorFlow", "R"] },
    ],
    projects: [
      { name: "Recommendation Engine", description: "ML-based content recommendation system", skills: ["Python", "TensorFlow", "SQL"], role: "ML Engineer", outcome: "15% improvement in recommendations" },
      { name: "Sentiment Analysis Tool", description: "NLP-based sentiment analysis for reviews", skills: ["Python", "Data Analysis"], role: "Data Scientist" },
    ],
    preferences: { desiredRoles: ["Data Scientist", "ML Engineer"], preferredIndustries: ["Technology", "Healthcare"], remote: true },
  },
  {
    id: "c3",
    name: "Priya Patel",
    email: "priya.p@email.com",
    avatar: "PP",
    skills: [
      { name: "React", level: 78, category: "framework", yearsOfExperience: 2 },
      { name: "Python", level: 80, category: "programming", yearsOfExperience: 3 },
      { name: "Django", level: 75, category: "framework", yearsOfExperience: 2 },
      { name: "PostgreSQL", level: 72, category: "database", yearsOfExperience: 2 },
      { name: "TypeScript", level: 70, category: "programming", yearsOfExperience: 1.5 },
      { name: "Figma", level: 82, category: "design", yearsOfExperience: 3 },
      { name: "UI/UX Design", level: 85, category: "design", yearsOfExperience: 3, certifications: ["Google UX Design"] },
      { name: "Leadership", level: 88, category: "softskill", yearsOfExperience: 3 },
    ],
    education: { degree: "B.S.", field: "Information Systems", institution: "UC Berkeley", gpa: 3.7, graduationYear: 2025 },
    experience: [
      { title: "UX Engineer Intern", company: "Google", durationMonths: 3, skills: ["React", "Figma", "UI/UX Design"] },
      { title: "Web Developer", company: "Freelance", durationMonths: 12, skills: ["React", "Python", "Django", "PostgreSQL"] },
    ],
    projects: [
      { name: "Healthcare Dashboard", description: "Patient data visualization dashboard", skills: ["React", "Python", "PostgreSQL", "UI/UX Design"], role: "Full Stack Developer & Designer", outcome: "Adopted by 3 clinics" },
      { name: "Portfolio Platform", description: "Creative portfolio site builder", skills: ["React", "TypeScript", "Figma"], role: "Lead Designer & Developer" },
    ],
    preferences: { desiredRoles: ["UX Engineer", "Full Stack Developer", "Product Designer"], preferredIndustries: ["Healthcare", "Education", "Technology"], remote: false, location: "San Francisco" },
  },
  {
    id: "c4",
    name: "Alex Rivera",
    email: "alex.r@email.com",
    avatar: "AR",
    skills: [
      { name: "Java", level: 85, category: "programming", yearsOfExperience: 3 },
      { name: "Spring Boot", level: 78, category: "framework", yearsOfExperience: 2 },
      { name: "Kubernetes", level: 72, category: "devops", yearsOfExperience: 1.5, certifications: ["CKA"] },
      { name: "AWS", level: 80, category: "cloud", yearsOfExperience: 2 },
      { name: "PostgreSQL", level: 75, category: "database", yearsOfExperience: 2 },
      { name: "React", level: 60, category: "framework", yearsOfExperience: 1 },
      { name: "System Design", level: 70, category: "programming", yearsOfExperience: 2 },
      { name: "Problem Solving", level: 90, category: "softskill", yearsOfExperience: 4 },
    ],
    education: { degree: "B.S.", field: "Software Engineering", institution: "Georgia Tech", gpa: 3.6, graduationYear: 2024 },
    experience: [
      { title: "Backend Developer Intern", company: "Amazon", durationMonths: 6, skills: ["Java", "AWS", "Kubernetes"] },
      { title: "Software Engineer Co-op", company: "IBM", durationMonths: 8, skills: ["Java", "Spring Boot", "PostgreSQL"] },
    ],
    projects: [
      { name: "Microservices Platform", description: "Scalable microservices architecture", skills: ["Java", "Spring Boot", "Kubernetes", "AWS"], role: "Backend Engineer", outcome: "Handled 10K req/s" },
      { name: "Cloud Migration Tool", description: "Automated cloud migration utility", skills: ["AWS", "Java", "PostgreSQL"], role: "Cloud Engineer" },
    ],
    preferences: { desiredRoles: ["Backend Engineer", "Cloud Engineer", "DevOps Engineer"], preferredIndustries: ["Technology", "Finance"], remote: true },
  },
  {
    id: "c5",
    name: "Emma Williams",
    email: "emma.w@email.com",
    avatar: "EW",
    skills: [
      { name: "React", level: 92, category: "framework", yearsOfExperience: 3.5, certifications: ["Meta React Developer"] },
      { name: "TypeScript", level: 90, category: "programming", yearsOfExperience: 3 },
      { name: "Next.js", level: 88, category: "framework", yearsOfExperience: 2 },
      { name: "Node.js", level: 82, category: "programming", yearsOfExperience: 2.5 },
      { name: "GraphQL", level: 75, category: "programming", yearsOfExperience: 1.5 },
      { name: "PostgreSQL", level: 68, category: "database", yearsOfExperience: 1 },
      { name: "Tailwind CSS", level: 90, category: "design", yearsOfExperience: 2 },
      { name: "Communication", level: 92, category: "softskill", yearsOfExperience: 4 },
    ],
    education: { degree: "B.S.", field: "Computer Science", institution: "Carnegie Mellon", gpa: 3.85, graduationYear: 2024 },
    experience: [
      { title: "Frontend Engineer Intern", company: "Stripe", durationMonths: 4, skills: ["React", "TypeScript", "Next.js"] },
      { title: "Web Developer Intern", company: "Shopify", durationMonths: 4, skills: ["React", "TypeScript", "GraphQL"] },
    ],
    projects: [
      { name: "SaaS Dashboard", description: "Analytics dashboard for SaaS metrics", skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"], role: "Frontend Lead", outcome: "500+ daily active users" },
      { name: "Real-time Collaboration Tool", description: "Google Docs-like collaboration app", skills: ["React", "Node.js", "GraphQL"], role: "Full Stack Developer" },
    ],
    preferences: { desiredRoles: ["Frontend Engineer", "Full Stack Developer"], preferredIndustries: ["Technology", "SaaS"], remote: true },
  },
  {
    id: "c6",
    name: "David Kim",
    email: "david.k@email.com",
    avatar: "DK",
    skills: [
      { name: "Python", level: 78, category: "programming", yearsOfExperience: 2 },
      { name: "React", level: 72, category: "framework", yearsOfExperience: 1.5 },
      { name: "Node.js", level: 68, category: "programming", yearsOfExperience: 1 },
      { name: "MongoDB", level: 65, category: "database", yearsOfExperience: 1 },
      { name: "Docker", level: 55, category: "devops", yearsOfExperience: 0.5 },
      { name: "Git", level: 75, category: "devops", yearsOfExperience: 2 },
      { name: "Teamwork", level: 80, category: "softskill", yearsOfExperience: 2 },
      { name: "TypeScript", level: 60, category: "programming", yearsOfExperience: 0.5 },
    ],
    education: { degree: "B.S.", field: "Computer Science", institution: "University of Michigan", gpa: 3.5, graduationYear: 2025 },
    experience: [
      { title: "Junior Developer", company: "Local Startup", durationMonths: 6, skills: ["Python", "React", "MongoDB"] },
    ],
    projects: [
      { name: "Task Manager App", description: "Kanban-style task management", skills: ["React", "Node.js", "MongoDB"], role: "Solo Developer" },
      { name: "Weather Dashboard", description: "Real-time weather visualization", skills: ["React", "Python"], role: "Developer" },
    ],
    preferences: { desiredRoles: ["Software Developer", "Full Stack Developer"], preferredIndustries: ["Technology", "Education"], remote: true },
  },
]

export const sampleProjects: Project[] = [
  {
    id: "p1",
    title: "Frontend Engineer Intern",
    company: "Google",
    description: "Join Google's Material Design team to build next-generation UI components for Google Workspace products. You will work with a team of senior engineers to develop accessible, performant React components used by millions of users.",
    requirements: [
      { skillName: "React", category: "framework", minimumLevel: 80, weight: 0.95, isRequired: true },
      { skillName: "TypeScript", category: "programming", minimumLevel: 75, weight: 0.90, isRequired: true },
      { skillName: "Node.js", category: "programming", minimumLevel: 60, weight: 0.50, isRequired: false },
      { skillName: "PostgreSQL", category: "database", minimumLevel: 50, weight: 0.30, isRequired: false },
      { skillName: "Git", category: "devops", minimumLevel: 70, weight: 0.40, isRequired: true },
      { skillName: "Communication", category: "softskill", minimumLevel: 70, weight: 0.60, isRequired: true },
    ],
    duration: "12 weeks",
    type: "internship",
    industry: "Technology",
    remote: false,
    location: "Mountain View, CA",
    teamSize: 8,
    postedBy: "Google Recruiting",
    postedDate: "2026-01-15",
    deadline: "2026-03-15",
    stipend: "$10,000/month",
  },
  {
    id: "p2",
    title: "Data Science Research Intern",
    company: "Meta",
    description: "Work with Meta's AI Research team on cutting-edge machine learning projects focused on content recommendation and user engagement. Apply statistical analysis and deep learning to solve real-world problems at massive scale.",
    requirements: [
      { skillName: "Python", category: "programming", minimumLevel: 85, weight: 0.95, isRequired: true },
      { skillName: "TensorFlow", category: "ai-ml", minimumLevel: 75, weight: 0.85, isRequired: true },
      { skillName: "SQL", category: "database", minimumLevel: 70, weight: 0.70, isRequired: true },
      { skillName: "Data Analysis", category: "data", minimumLevel: 80, weight: 0.90, isRequired: true },
      { skillName: "R", category: "programming", minimumLevel: 50, weight: 0.30, isRequired: false },
      { skillName: "Teamwork", category: "softskill", minimumLevel: 65, weight: 0.50, isRequired: true },
    ],
    duration: "16 weeks",
    type: "internship",
    industry: "Technology",
    remote: true,
    teamSize: 5,
    postedBy: "Meta Research",
    postedDate: "2026-01-20",
    deadline: "2026-03-01",
    stipend: "$12,000/month",
  },
  {
    id: "p3",
    title: "Full Stack Developer Project",
    company: "Stripe",
    description: "Build a comprehensive payment analytics dashboard for Stripe's merchant tools. This project involves both frontend development with React and backend API development with Node.js, integrating with Stripe's payment infrastructure.",
    requirements: [
      { skillName: "React", category: "framework", minimumLevel: 75, weight: 0.90, isRequired: true },
      { skillName: "TypeScript", category: "programming", minimumLevel: 70, weight: 0.85, isRequired: true },
      { skillName: "Node.js", category: "programming", minimumLevel: 70, weight: 0.80, isRequired: true },
      { skillName: "PostgreSQL", category: "database", minimumLevel: 65, weight: 0.75, isRequired: true },
      { skillName: "UI/UX Design", category: "design", minimumLevel: 50, weight: 0.40, isRequired: false },
      { skillName: "Communication", category: "softskill", minimumLevel: 60, weight: 0.50, isRequired: true },
    ],
    duration: "10 weeks",
    type: "project",
    industry: "Finance",
    remote: true,
    teamSize: 4,
    postedBy: "Stripe Engineering",
    postedDate: "2026-02-01",
    deadline: "2026-04-01",
    stipend: "$8,000/month",
  },
  {
    id: "p4",
    title: "Cloud Infrastructure Intern",
    company: "Amazon Web Services",
    description: "Design and implement scalable cloud infrastructure solutions for AWS customers. Work on containerization, CI/CD pipelines, and infrastructure-as-code to support enterprise-grade deployments.",
    requirements: [
      { skillName: "AWS", category: "cloud", minimumLevel: 70, weight: 0.95, isRequired: true },
      { skillName: "Java", category: "programming", minimumLevel: 75, weight: 0.85, isRequired: true },
      { skillName: "Kubernetes", category: "devops", minimumLevel: 65, weight: 0.80, isRequired: true },
      { skillName: "PostgreSQL", category: "database", minimumLevel: 60, weight: 0.50, isRequired: false },
      { skillName: "System Design", category: "programming", minimumLevel: 60, weight: 0.70, isRequired: true },
      { skillName: "Problem Solving", category: "softskill", minimumLevel: 70, weight: 0.55, isRequired: true },
    ],
    duration: "12 weeks",
    type: "internship",
    industry: "Technology",
    remote: false,
    location: "Seattle, WA",
    teamSize: 6,
    postedBy: "AWS Recruiting",
    postedDate: "2026-02-05",
    deadline: "2026-03-20",
    stipend: "$9,500/month",
  },
  {
    id: "p5",
    title: "UX Engineering Intern",
    company: "Apple",
    description: "Bridge the gap between design and engineering on Apple's Human Interface team. Create pixel-perfect implementations of next-generation user interfaces for Apple products, focusing on accessibility and performance.",
    requirements: [
      { skillName: "React", category: "framework", minimumLevel: 70, weight: 0.80, isRequired: true },
      { skillName: "UI/UX Design", category: "design", minimumLevel: 75, weight: 0.95, isRequired: true },
      { skillName: "Figma", category: "design", minimumLevel: 70, weight: 0.75, isRequired: true },
      { skillName: "TypeScript", category: "programming", minimumLevel: 65, weight: 0.70, isRequired: true },
      { skillName: "Tailwind CSS", category: "design", minimumLevel: 60, weight: 0.50, isRequired: false },
      { skillName: "Leadership", category: "softskill", minimumLevel: 60, weight: 0.40, isRequired: false },
    ],
    duration: "14 weeks",
    type: "internship",
    industry: "Technology",
    remote: false,
    location: "Cupertino, CA",
    teamSize: 10,
    postedBy: "Apple Design",
    postedDate: "2026-01-25",
    deadline: "2026-03-10",
    stipend: "$11,000/month",
  },
  {
    id: "p6",
    title: "Backend API Developer",
    company: "Spotify",
    description: "Develop and optimize backend APIs for Spotify's music streaming platform. Work on high-throughput systems handling millions of requests, focusing on low-latency data retrieval and playlist recommendations.",
    requirements: [
      { skillName: "Python", category: "programming", minimumLevel: 75, weight: 0.85, isRequired: true },
      { skillName: "PostgreSQL", category: "database", minimumLevel: 70, weight: 0.80, isRequired: true },
      { skillName: "Docker", category: "devops", minimumLevel: 60, weight: 0.60, isRequired: false },
      { skillName: "Node.js", category: "programming", minimumLevel: 65, weight: 0.70, isRequired: false },
      { skillName: "Git", category: "devops", minimumLevel: 65, weight: 0.40, isRequired: true },
      { skillName: "Teamwork", category: "softskill", minimumLevel: 60, weight: 0.45, isRequired: true },
    ],
    duration: "8 weeks",
    type: "project",
    industry: "Entertainment",
    remote: true,
    teamSize: 3,
    postedBy: "Spotify Engineering",
    postedDate: "2026-02-10",
    deadline: "2026-04-15",
    stipend: "$7,500/month",
  },
]
